In [48]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_selection import RFECV
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold,train_test_split

from imblearn.over_sampling import SMOTE

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix

In [2]:
data = pd.read_csv("SalaryData_train.csv")

In [3]:
data.head(10)

age          workclass   education  educationno           maritalstatus  \
0   39          State-gov   Bachelors           13           Never-married   
1   50   Self-emp-not-inc   Bachelors           13      Married-civ-spouse   
2   38            Private     HS-grad            9                Divorced   
3   53            Private        11th            7      Married-civ-spouse   
4   28            Private   Bachelors           13      Married-civ-spouse   
5   37            Private     Masters           14      Married-civ-spouse   
6   49            Private         9th            5   Married-spouse-absent   
7   52   Self-emp-not-inc     HS-grad            9      Married-civ-spouse   
8   31            Private     Masters           14           Never-married   
9   42            Private   Bachelors           13      Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   
5     Exec-managerial            Wife   White   Female            0   
6       Other-service   Not-in-family   Black   Female            0   
7     Exec-managerial         Husband   White     Male            0   
8      Prof-specialty   Not-in-family   White   Female        14084   
9     Exec-managerial         Husband   White     Male         5178   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K  
5            0            40   United-States   <=50K  
6            0            16         Jamaica   <=50K  
7            0            45   United-States    >50K  
8            0            50   United-States    >50K  
9            0            40   United-States    >50K

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            30161 non-null  int64 
 1   workclass      30161 non-null  object
 2   education      30161 non-null  object
 3   educationno    30161 non-null  int64 
 4   maritalstatus  30161 non-null  object
 5   occupation     30161 non-null  object
 6   relationship   30161 non-null  object
 7   race           30161 non-null  object
 8   sex            30161 non-null  object
 9   capitalgain    30161 non-null  int64 
 10  capitalloss    30161 non-null  int64 
 11  hoursperweek   30161 non-null  int64 
 12  native         30161 non-null  object
 13  Salary         30161 non-null  object
dtypes: int64(5), object(9)
memory usage: 3.2+ MB


In [5]:
ed=data.education.unique()

grad = {ed[0]:'UG',ed[1]:'HighSchool',ed[2]:'HighSchool',ed[3]:'PG',ed[4]:'School',ed[5]:'HighSchool'
       ,ed[6]:'AA',ed[7]:'School',ed[8]:'Ph.D',ed[9]:'AV',ed[10]:'HighSchool',ed[11]:'School',
       ed[12]:'School',ed[13]:'School',ed[14]:'School',ed[15]:'HighSchool'}

In [6]:
data['education'] = data['education'].map(grad)

In [7]:
data.shape

(30161, 14)

In [8]:
#data['workclass'] = LabelEncoder().fit_transform(data['workclass'])

In [9]:
#data['maritalstatus'] = LabelEncoder().fit_transform(data['maritalstatus'])

In [10]:
#data['occupation'] = LabelEncoder().fit_transform(data['occupation'])

In [11]:
data.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov          UG           13        Never-married   
1   50   Self-emp-not-inc          UG           13   Married-civ-spouse   
2   38            Private  HighSchool            9             Divorced   
3   53            Private  HighSchool            7   Married-civ-spouse   
4   28            Private          UG           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [12]:
#data['relationship'] = LabelEncoder().fit_transform(data['relationship'])

In [13]:
#data['race'] = LabelEncoder().fit_transform(data['race'])

In [14]:
#data['sex'] = LabelEncoder().fit_transform(data['sex'])

In [15]:
#data['Salary'] = LabelEncoder().fit_transform(data['Salary'])

In [16]:
data.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov          UG           13        Never-married   
1   50   Self-emp-not-inc          UG           13   Married-civ-spouse   
2   38            Private  HighSchool            9             Divorced   
3   53            Private  HighSchool            7   Married-civ-spouse   
4   28            Private          UG           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [17]:
#data['native'] = LabelEncoder().fit_transform(data['native'])

In [18]:
data.head(10)

age          workclass   education  educationno           maritalstatus  \
0   39          State-gov          UG           13           Never-married   
1   50   Self-emp-not-inc          UG           13      Married-civ-spouse   
2   38            Private  HighSchool            9                Divorced   
3   53            Private  HighSchool            7      Married-civ-spouse   
4   28            Private          UG           13      Married-civ-spouse   
5   37            Private          PG           14      Married-civ-spouse   
6   49            Private      School            5   Married-spouse-absent   
7   52   Self-emp-not-inc  HighSchool            9      Married-civ-spouse   
8   31            Private          PG           14           Never-married   
9   42            Private          UG           13      Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   
5     Exec-managerial            Wife   White   Female            0   
6       Other-service   Not-in-family   Black   Female            0   
7     Exec-managerial         Husband   White     Male            0   
8      Prof-specialty   Not-in-family   White   Female        14084   
9     Exec-managerial         Husband   White     Male         5178   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K  
5            0            40   United-States   <=50K  
6            0            16         Jamaica   <=50K  
7            0            45   United-States    >50K  
8            0            50   United-States    >50K  
9            0            40   United-States    >50K

In [19]:
objCol = data.select_dtypes('object')

objCol
print(objCol.columns)

for x in objCol.columns:
    print(x)

Index(['workclass', 'education', 'maritalstatus', 'occupation', 'relationship',
       'race', 'sex', 'native', 'Salary'],
      dtype='object')
workclass
education
maritalstatus
occupation
relationship
race
sex
native
Salary


In [20]:
data.shape

(30161, 14)

In [21]:
def Labeling(col,dataFrame):
    
    for x in col:
        dataFrame[x] = LabelEncoder().fit_transform(data[x])
        
    return dataFrame

In [22]:
sal = Labeling(objCol.columns,data)

In [23]:
data.shape

(30161, 14)

In [24]:
data.head(10)

age  workclass  education  educationno  maritalstatus  occupation  \
0   39          5          6           13              4           0   
1   50          4          6           13              2           3   
2   38          2          2            9              0           5   
3   53          2          2            7              2           5   
4   28          2          6           13              2           9   
5   37          2          3           14              2           3   
6   49          2          5            5              3           7   
7   52          4          2            9              2           3   
8   31          2          3           14              4           9   
9   42          2          6           13              2           3   

   relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  \
0             1     4    1         2174            0            40      37   
1             0     4    1            0            0            13      37   
2             1     4    1            0            0            40      37   
3             0     2    1            0            0            40      37   
4             5     2    0            0            0            40       4   
5             5     4    0            0            0            40      37   
6             1     2    0            0            0            16      21   
7             0     4    1            0            0            45      37   
8             1     4    0        14084            0            50      37   
9             0     4    1         5178            0            40      37   

   Salary  
0       0  
1       0  
2       0  
3       0  
4       0  
5       0  
6       0  
7       1  
8       1  
9       1

In [25]:
ss = StandardScaler().fit_transform(data.drop('Salary',1))

In [26]:
sal = pd.DataFrame(ss,columns = data.columns[:-1])

In [27]:
sal['Salary'] = data.Salary

In [28]:
xTrain,xTest , yTrain,yTest = train_test_split(sal.drop('Salary',1),sal.Salary,test_size=0.2)

In [29]:
rf = RandomForestClassifier(n_estimators= 100)

In [30]:
rfe = RFECV(estimator=rf,cv=10,scoring='accuracy')

In [31]:
rfe.fit(xTrain,yTrain)

RFECV(cv=10,
      estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                       class_weight=None, criterion='gini',
                                       max_depth=None, max_features='auto',
                                       max_leaf_nodes=None, max_samples=None,
                                       min_impurity_decrease=0.0,
                                       min_impurity_split=None,
                                       min_samples_leaf=1, min_samples_split=2,
                                       min_weight_fraction_leaf=0.0,
                                       n_estimators=100, n_jobs=None,
                                       oob_score=False, random_state=None,
                                       verbose=0, warm_start=False),
      min_features_to_select=1, n_jobs=None, scoring='accuracy', step=1,
      verbose=0)

In [32]:
rfe.support_

array([False, False, False,  True, False, False,  True, False, False,
        True, False, False, False])

In [33]:
 rfe.estimator_.feature_importances_

array([0.26901659, 0.42817095, 0.30281247])

In [34]:
rfe.grid_scores_

array([0.74883982, 0.80089513, 0.84503482, 0.83753283, 0.82650853,
       0.82978199, 0.8306528 , 0.83438291, 0.84325247, 0.84250661,
       0.84159505, 0.84279643, 0.84221634])

In [36]:
print(np.where(rfe.support_ == False)[0])

[ 0  1  2  4  5  7  8 10 11 12]


In [37]:
rfe.n_features_

3

In [38]:
X,xTest, Y,yTest = train_test_split(sal.drop('Salary',1),sal.Salary,test_size=0.2)

In [40]:
xTrain,yTrain = SMOTE(k_neighbors=4).fit_sample(X,Y)

In [41]:
rf = RandomForestClassifier()

In [42]:
rfe = RFECV(estimator=rf,cv=10,scoring= 'accuracy')

In [43]:
rfe.fit(xTrain,yTrain)

RFECV(cv=10,
      estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                       class_weight=None, criterion='gini',
                                       max_depth=None, max_features='auto',
                                       max_leaf_nodes=None, max_samples=None,
                                       min_impurity_decrease=0.0,
                                       min_impurity_split=None,
                                       min_samples_leaf=1, min_samples_split=2,
                                       min_weight_fraction_leaf=0.0,
                                       n_estimators=100, n_jobs=None,
                                       oob_score=False, random_state=None,
                                       verbose=0, warm_start=False),
      min_features_to_select=1, n_jobs=None, scoring='accuracy', step=1,
      verbose=0)

In [44]:
rfe.support_

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [46]:
nb = GaussianNB().fit(xTrain,yTrain)

In [47]:
pred = nb.predict(xTest)

In [49]:
accuracy_score(yTest,pred)

0.8206530747555113